# Generated by Django 3.2.7 on 2021-09-24 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_company_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='company',
            name='time_updated',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.AddField(
            model_name='company',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создана'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлена'),
        ),
        migrations.AddField(
            model_name='employee',
            name='third_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='company',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='_app_company_companies_+', to='app.Company', verbose_name='Партнеры'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус работы'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
    ]
