# Generated by Django 3.2.7 on 2021-09-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210930_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус партнерства'),
        ),
    ]
